ContextProcessor/ContextProcessor/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('context/', include("LoginService.urls")),
    path('middleware/', include("MiddleWare.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ContextProcessor/LoginService/urls.py
from django.urls import path 
from . import views

app_name = "ContextView"

urlpatterns = [
    path("", views.index, name = "Index"),
    path("video", views.videoIndex, name = "VideoIndex"),
    path("book", views.bookIndex, name = "BookIndex"),
    path("login", views.LoginView.as_view(), name = "Login"),
    path("register", views.RegisterView.as_view(), name = "Register"),
    path("debug", views.debugIndex, name = "DebugIndex"),
    path("messages", views.messageIndex, name = "MessageIndex"),
    path("media", views.mediaIndex, name = "MediaIndex")
]

ContextProcessor/MiddleWare/urls.py
from django.urls import path
from . import views

app_name = "MiddleWareView"

urlpatterns = [
    path("", views.index, name = "Index")
]

ContextProcessor/LoginService/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length = 50)
    password = models.CharField(max_length = 100)
    nickname = models.CharField(max_length = 50)

    class Meta:
        db_table = "user"

ContextProcessor/LoginService/forms.py
from django import forms
from .models import User

class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = "__all__"
        labels = {
            "username": "用户名",
            "password": "密码",
            "nickname": "昵称"
        }


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = ["nickname"]
        labels = {
            "username": "用户名",
            "password": "密码"
        }

ContextProcessor/LoginService/views.py
from django.shortcuts import render
from django.views.generic.base import View
from .forms import RegisterForm, LoginForm
from .models import User
from django.shortcuts import redirect, reverse
from django.http import HttpResponse


# Create your views here.
def index(request):
    # userId = request.session.get("userId")
    # context = {}
    # try:
    #     user = User.objects.get(pk = userId)
    #     context["user"] = user
    #     context["isLogin"] = True
    # except :
    #     context["isLogin"] = False
    print("redenr之前")
    response = render(request, "login_service_index.html")
    print("redenr之后")
    return response


class LoginView(View):

    def get(self, request, *args, **kwargs):
        return render(request, "login.html", context = {"form": LoginForm()})

    def post(self, request, *args, **kwargs):
        loginForm = LoginForm(request.POST)
        if loginForm.is_valid():
            username = loginForm.cleaned_data.get("username")
            password = loginForm.cleaned_data.get("password")
            user = User.objects.filter(username = username, password = password).first()
            if user :
                request.session["userId"] = user.id
                return redirect(reverse("ContextView:Index"))
            else :
                return HttpResponse("账号不存在")
        else :
            print(loginForm.get_json_data())
            return HttpResponse("登陆失败")


class RegisterView(View):

    def get(self, request, *args, **kwargs):
        return render(request, "register.html", context = {"form": RegisterForm()})
    
    def post(self, request, *args, **kwargs):
        registerForm = RegisterForm(request.POST)
        if registerForm.is_valid():
            username = registerForm.cleaned_data.get("username")
            isExists = User.objects.filter(username = username).exists()
            if not isExists:
                registerForm.save()
                return redirect(reverse("ContextView:Login"))
            else :
                return HttpResponse("用户名已存在")
        else :
            print(registerForm.get_json_data())
            return HttpResponse("注册失败")



def videoIndex(request):
    return render(request, "login_service_video_index.html")

def bookIndex(request):
    return render(request, "login_service_book_index.html")

from django.template.context_processors import debug, request
from django.contrib.auth.context_processors import auth


def debugIndex(request):
    users = User.objects.all()
    for user in users:
        print(user)
    return render(request, "debug_service.html")


# from django.contrib.messages.context_processors import messages
from django.contrib import messages
from django.contrib.messages.api import get_messages
from django.contrib.messages import DEFAULT_TAGS, DEFAULT_LEVELS

def messageIndex(request):

    messages.set_level(request, 10)

    messages.info(request, "InfoMessage")
    messages.debug(request, "DebugMessage")
    messages.warning(request, "WarningMessage")
    messages.success(request, "SuccessMessage")
    messages.error(request, "ErrorMessage")

    messageList = get_messages(request)
    
    for mes in messageList:
        print(mes.__dict__)

    print(DEFAULT_TAGS)
    print(DEFAULT_LEVELS)
    return render(request, "messge_service.html")

# {'level': 20, 'message': 'InfoMessage', 'extra_tags': ''}
# {'level': 10, 'message': 'DebugMessage', 'extra_tags': ''}
# {'level': 30, 'message': 'WarningMessage', 'extra_tags': ''}
# {'level': 25, 'message': 'SuccessMessage', 'extra_tags': ''}
# {'level': 40, 'message': 'ErrorMessage', 'extra_tags': ''}
# {10: 'debug', 20: 'info', 25: 'success', 30: 'warning', 40: 'error'}
# {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}


def mediaIndex(request):
    return render(request, "media_url_service.html")

ContextProcessor/MiddleWare/views.py
from django.shortcuts import render
from django.middleware.common import CommonMiddleware
from django.middleware.gzip import GZipMiddleware
from django.middleware.cache import UpdateCacheMiddleware, FetchFromCacheMiddleware

# Create your views here.
def index(request):
    inner = InnerTest()
    inner()
    inner()
    inner().print("Test")
    inner.print("Test")

    return render(request, "middleware_index.html")


class InnerTest():

    def __init__(self):
        print("__init__")

    def __call__(self):
        print("__call__")
        return self

    def print(self, params):
        print(params)

ContextProcessor/templates/debug_service.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <p>Debug测试首页</p>
    <p>{{ debug }}</p>
    <p>{{ sql_queries }}</p>
</body>
</html>

ContextProcessor/templates/login.html
{% extends "login_service_base.html" %}

{% block abstractContent %}
    <form action="" method="post">
        <table>
            {{ form.as_table }}

            <tr>
                <td></td>
                <td><input type="submit" value="登陆"></td>
            </tr>
        </table>
    </form>
{% endblock %}

ContextProcessor/templates/login_service_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Brand</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'ContextView:Index' %}">首页 <span class="sr-only">(current)</span></a></li>
                    <li class="active"><a href="{% url 'ContextView:VideoIndex' %}">视频 <span class="sr-only">(current)</span></a></li>
                    <li class="active"><a href="{% url 'ContextView:BookIndex' %}">图书 <span class="sr-only">(current)</span></a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if isLogin %}
                        <li><a>{{ user.nickname }} </a></li>
                    {% else %}
                        <li><a href="{% url 'ContextView:Login' %}">登陆</a></li>
                        <li><a href="{% url 'ContextView:Register' %}">注册</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    {% block abstractContent %}
        LoginService首页
    {% endblock %}

</body>

</html>

ContextProcessor/templates/login_service_book_index.html
{% extends "login_service_index.html" %}

{% block abstractContent %}
    
{% endblock %}

ContextProcessor/templates/login_service_index.html
{% extends "login_service_base.html" %}

{% block abstractContent %}
    {{ block.super }}
{% endblock %}

ContextProcessor/templates/login_service_video_index.html
{% extends "login_service_index.html" %}

{% block abstractContent %}
    
{% endblock %}

ContextProcessor/templates/media_url_service.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <img src="{{ MEDIA_URL }}icon.jpg" alt="" srcset="">
</body>
</html>

ContextProcessor/templates/messge_service.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    Messages主页
    <ul>
    {% for message in messages %}
        <li>{{ message.message }}</li>
    {% endfor %}
    </ul>
</body>
</html>

ContextProcessor/templates/middleware_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    MiddleWare处理器
</body>
</html>

ContextProcessor/templates/register.html
{% extends "login_service_base.html" %}

{% block abstractContent %}
    <form action="" method="post">
        <table>
            {{ form.as_table }}
            
            <tr>
                <td></td>
                <td><input type="submit" value="注册"></td>
            </tr>
        </table>
    </form>
{% endblock %}